import { CollectiveCardData } from "@/components/collectives/CollectiveCard";

export const MOCK_COLLECTIVES: CollectiveCardData[] = [
  {
    id: "anchorfund",
    name: "AnchorFund by Ennovate Ventures",
    logoColor: "#d4a843",
    logoInitials: "AF",
    type: "Real Estate",
    locations: ["Eastern Africa"],
    memberCount: 2,
    visibility: "Public",
    paymentModel: "Paid",
    managers: [
      { name: "Gloria Wafula", initials: "GW" },
      { name: "Fr.", initials: "FR" },
    ],
  },
  {
    id: "bitesize-capital",
    name: "Bitesize Capital",
    logoColor: "#1a1a1a",
    logoInitials: "B",
    type: "Venture Capital (Startups)",
    locations: ["Western Europe"],
    memberCount: 1,
    visibility: "Public",
    paymentModel: "Free",
    managers: [
      { name: "Team Ecobond", initials: "TE" },
    ],
  },
  {
    id: "diaspora-house",
    name: "Diaspora House",
    logoColor: "#e5e7eb",
    logoInitials: "DH",
    type: "Real Estate",
    locations: [],
    memberCount: 54,
    visibility: "Public",
    paymentModel: "Free",
    managers: [
      { name: "Joe Kinvi", initials: "JK" },
      { name: "Gloria", initials: "GL" },
    ],
  },
  {
    id: "h2ventures",
    name: "H2Ventures",
    logoColor: "#7c3aed",
    logoInitials: "H2",
    type: "Alternative Investments",
    locations: ["Eastern Africa"],
    memberCount: 2,
    visibility: "Private",
    paymentModel: "Free",
    managers: [
      { name: "Joe Kinvi", initials: "JK" },
      { name: "Holger", initials: "HO" },
    ],
  },
  {
    id: "hoaq",
    name: "HoaQ",
    logoColor: "#065f46",
    logoInitials: "HQ",
    type: "Venture Capital (Startups)",
    locations: ["Northern America", "Northern Europe"],
    memberCount: 1230,
    visibility: "Private",
    paymentModel: "Paid",
    managers: [
      { name: "Folakemi Osho", initials: "FO" },
      { name: "J.", initials: "JO" },
    ],
  },
  {
    id: "kigo-collective",
    name: "Kigo Collective",
    logoColor: "#1d4ed8",
    logoInitials: "KC",
    type: "Venture Capital (Startups)",
    locations: ["Eastern Africa"],
    memberCount: 21,
    visibility: "Public",
    paymentModel: "Free",
    managers: [
      { name: "MT", initials: "MT" },
      { name: "Stephen Kauma", initials: "SK" },
    ],
  },
  {
    id: "originative",
    name: "Originative: Invest in Culture",
    logoColor: "#0ea5e9",
    logoInitials: "OC",
    type: "Alternative Investments",
    locations: ["Western Asia"],
    memberCount: 0,
    visibility: "Public",
    paymentModel: "Paid",
    managers: [
      { name: "AA", initials: "AA" },
      { name: "Abeer Abu Shmeis", initials: "AS" },
    ],
  },
  {
    id: "pula-kollektive",
    name: "Pula Kollektive",
    logoColor: "#1a1a1a",
    logoInitials: "PK",
    type: "Venture Capital (Startups)",
    locations: ["Southern Africa"],
    memberCount: 6,
    visibility: "Public",
    paymentModel: "Free",
    managers: [
      { name: "TM", initials: "TM" },
      { name: "Torti Ama-Njoku", initials: "TN" },
    ],
  },
  {
    id: "raise-by-borderless",
    name: "Raise by Ecobond",
    logoColor: "#1b3a2d",
    logoInitials: "Raise",
    type: "Venture Capital (Startups)",
    locations: ["Northern Africa"],
    memberCount: 0,
    visibility: "Public",
    paymentModel: "Free",
    managers: [{ name: "Ecobond", initials: "EC" }],
  },
  {
    id: "realcorp-capital",
    name: "RealCorp Capital",
    logoColor: "#dc2626",
    logoInitials: "RC",
    type: "Venture Capital (Startups)",
    locations: ["Northern America", "Northern Europe"],
    memberCount: 0,
    visibility: "Public",
    paymentModel: "Free",
    managers: [{ name: "Team", initials: "TM" }],
  },
  {
    id: "serengeti-angels",
    name: "Serengeti Business Angels Netw...",
    logoColor: "#374151",
    logoInitials: "SA",
    type: "Venture Capital (Startups)",
    locations: ["Eastern Africa"],
    memberCount: 3,
    visibility: "Public",
    paymentModel: "Paid",
    managers: [{ name: "Admin", initials: "AD" }],
  },
  {
    id: "ecosystem-commission",
    name: "The Ecosystem Commission",
    logoColor: "#dc2626",
    logoInitials: "EC",
    type: "Venture Capital (Startups)",
    locations: ["Eastern Africa", "Northern America"],
    memberCount: 1,
    visibility: "Public",
    paymentModel: "Paid",
    managers: [{ name: "Commission", initials: "EC" }],
  },
];
